backend env file

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -180,15 +180,15 @@ jobs:
             fi
 
 
-            if [ ! -f "$PROJECT_DIR/backend/.env" ]; then
+            if [ ! -f "$PROJECT_DIR/backend/.env.production" ]; then
               echo "📝 Creating backend .env file (first time)..."
-              cat > $PROJECT_DIR/backend/.env <<'ENVEOF'
+              cat > $PROJECT_DIR/backend/.env.production <<'ENVEOF'
             NODE_ENV=production
             JWT_SECRET=${{ secrets.JWT_SECRET }}
             PORT=5000
             ENVEOF
             else
-              echo "✅ Backend .env already exists, skipping creation."
+              echo "✅ Backend .env.production already exists, skipping creation."
             fi
 
             if [ ! -f "$PROJECT_DIR/frontend/.env" ]; then
@@ -241,20 +241,16 @@ jobs:
             fi
             echo "AWS CLI: $(aws --version)"
 
-            # # ----- IAM role sanity checks -----
-            # if ! aws sts get-caller-identity >/dev/null 2>&1; then
-            #    echo "ERROR: No AWS credentials on EC2. Attach an EC2 IAM role with ECR permissions." && exit 1
-            # fi
 
             echo "🔑 Logging in to ECR..."
             aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | sudo docker login --username AWS --password-stdin $ECR_URL
 
-            # ----- ECR auth for Docker (use sudo if docker-compose uses sudo) -----
-            if aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | sudo docker login --username AWS --password-stdin "$ECR_URL"; then
-              echo "✅ ECR login OK: $ECR_URL"
-            else
-              echo "❌ ECR login failed: $ECR_URL" && exit 1
-            fi
+            # # ----- ECR auth for Docker (use sudo if docker-compose uses sudo) -----
+            # if aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | sudo docker login --username AWS --password-stdin "$ECR_URL"; then
+            #   echo "✅ ECR login OK: $ECR_URL"
+            # else
+            #   echo "❌ ECR login failed: $ECR_URL" && exit 1
+            # fi
 
            
 
